### ISSUE TITLE
Possible to show battery-status in the menubar itself?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [pvdabeel/mytesla#1]
Title says it all! I saw that this was in Python, so perhaps not (I suspect you'd have to write a little Swift to implement that.)

Still thought I'd ask!

**Comment by pvdabeel** [comment]
Sure, quite easy. Should be implemented in the next commit

**Comment by pvdabeel** [comment]
Added in the last commit. If you have only one car on your account and you want the app to display the battery status in the menu bar, open mytesla.15m.py in your favourite text editor and change 

`_BATTERY_MENUBAR_ = False`

to 

`_BATTERY_MENUBAR_ = True`

(on line 36) 

You should get something like this: 

<img width="93" alt="menubar-example" src="https://user-images.githubusercontent.com/32812891/111868427-0a7e5900-897a-11eb-937e-11fff8d3f54f.png">
